projeto/urls.py
from django.contrib import admin
from django.urls import path
from projeto.views import CategoriaListView, CategoriaCreateView, CategoriaUpdateView, CategoriaDeleteView, ProdutoListView, ProdutoCreateView, ProdutoUpdateView, ProdutoDeleteView

urlpatterns = [
    #categoria
    path('categoria/', CategoriaListView.as_view(), name='categoria_list'),
    path('categoria/create/', CategoriaCreateView.as_view(), name='categoria_create'),
    path('categoria/<int:pk>/update/', CategoriaUpdateView.as_view(), name='categoria_update'),
    path('categoria/<int:pk>/delete/', CategoriaDeleteView.as_view(), name='categoria_delete'),
    #produto
    path('produto/', ProdutoListView.as_view(), name='produto_list'),
    path('produto/create/', ProdutoCreateView.as_view(), name='produto_create'),
    path('produto/<int:pk>/update/', ProdutoUpdateView.as_view(), name='produto_update'),
    path('produto/<int:pk>/delete/', ProdutoDeleteView.as_view(), name='produto_delete'),
]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('projeto.urls')),
    path('', include('movimentacao.urls')),
    path('', include('usuarios.urls')),
    path('', include('homepage.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movimentacao/models.py
from typing import Iterable
from django.db import models
class Movimentacao(models.Model):
    TIPO_MOVIMENTACAO = [
        ('E', 'Entrada'),
        ('S', 'Saida'),
    ]
    produto = models.ForeignKey('projeto.Produto', on_delete=models.CASCADE)
    quantidade = models.IntegerField()
    data = models.DateField(auto_now_add=True)
    tipo = models.CharField(max_length=1, choices=TIPO_MOVIMENTACAO)
    valor_total = models.DecimalField(max_digits=10, decimal_places=2, editable=False)

    def save(self, *args, **kwargs):
        self.valor_total = self.quantidade * self.produto.valor
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.produto} - {self.quantidade} unidades em {self.data} - Total: R$ {self.valor_total}'

projeto/models.py
from django.db import models

class Categoria(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(max_length=300)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.nome
    
class Produto(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(max_length=300)
    valor = models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    ativo = models.BooleanField(default=True)
    estado = models.CharField(max_length=1, choices=[('N', 'Novo'), ('U', 'Usado')])
    imagem = models.ImageField(upload_to='produto/', null=True, blank=True)

    def __str__(self):
        return self.nome

projeto/forms.py
from django import forms
from projeto.models import Categoria, Produto


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome', 'descricao',]
        labels = {
            'nome': 'Nome da categoria',
            'descricao': 'Descrição da Categoria',
        }

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nome', 'valor', 'descricao', 'categoria', 'imagem', 'estado'] 
        labels = {
            'nome': 'Nome do Produto',
            'descricao': 'Descrição do Produto',
            'valor': 'Valor(R$)',
            'categoria': 'Categoria',
            'imagem': 'Imagem',
            'estado': 'Estado'
        }     
  

projeto/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from projeto.models import Categoria, Produto
from projeto.forms import CategoriaForm, ProdutoForm


class CategoriaListView(ListView):
    model = Categoria
    template_name = 'categoria_list.html'

class CategoriaCreateView(CreateView):
    model = Categoria
    template_name = 'categoria_form.html'
    form_class = CategoriaForm
    success_url = reverse_lazy('categoria_list')

class CategoriaUpdateView(UpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'categoria_form.html'
    success_url = reverse_lazy('categoria_list')

class CategoriaDeleteView(DeleteView):
    model = Categoria
    template_name = 'categoria_confirm_delete.html'
    success_url = reverse_lazy('categoria_list')

class ProdutoListView(ListView):
    model = Produto
    template_name = 'produto_list.html'

class ProdutoCreateView(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm
    success_url = reverse_lazy('produto_list')

class ProdutoUpdateView(UpdateView):
    model = Produto
    form_class = ProdutoForm
    template_name = 'produto_form.html'
    success_url = reverse_lazy('produto_list')

class ProdutoDeleteView(DeleteView):
    model = Produto
    template_name = 'produto_confirm_delete.html'
    success_url = reverse_lazy('produto_list')

projeto/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Projeto Semestre{% endblock %}</title> {% load static%}
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">

    {% comment %} Ícone de Menu da navbar {% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

</head>
<body>

        {% comment %}
        <img class="logo" src="{% static 'img/logo.png' %}" alt="">
        <div class="btnacesso">
            <a class="btn" href="{% url 'homepage'%}">Home</a>
            <a class="btn" href="{% url 'produto_list'%}">Produtos</a>
            <a class="btn" href="{% url 'categoria_list'%}">Categoria</a>
            <a class="btn" href="{% url 'movimentacao_list'%}">Movimentação</a>
            <a class="btn" href="{% url 'profile' %}">Perfil</a>
            <form action="{% url "logout" %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btnv">Sair</button>
            </form>
        </div>
        {% endcomment %}

        <nav>
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
                <i class="fas fa-bars" ></i>
            </label>


            <div class="logo-container">
                <img class="logo" src="{% static 'img/logo-removebg-preview.png' %}" alt="logo">
            </div>
            <ul>
                <li><a href="{% url 'homepage'%}">Home</a></li>
                <li><a href="{% url 'produto_list'%}">Produtos</a></li>
                <li><a href="{% url 'categoria_list'%}">Categorias</a></li>
                <li><a href="{% url 'movimentacao_list'%}">Movimentação</a></li>
                <li><a href="{% url 'profile' %}">Perfil</a></li>
                <li><form action="{% url "logout" %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btnv" id="btn-logout">Sair</button>
                </form></li>
            </ul>
        </nav>
    {% comment %} Espaço do fechamento header, lembrar de abrir la em cima se for por de volta{% endcomment %}
    <div class="container">
    {% block content %} {% endblock %}
    </div>
    <footer></footer>
</body>
</html>

projeto/templates/categoria_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Excluir Categoria{% endblock %}

{% block content %}
    <h2>Excluir Categoria</h2>

    <p>Tem certeza de que deseja excluir a categoria <strong>{{ object.nome }}</strong>?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btnv">Confirmar Exclusão</button>
        <a class="btn" href="{% url 'categoria_list' %}">Cancelar</a>
    </form>
{% endblock %}

projeto/templates/categoria_form.html
{% extends 'base.html' %}

{% block title %}Formulário de Categoria{% endblock %}

{% block content %}
    <h2>{% if object %}Editar Categoria{% else %}Nova Categoria{% endif %}</h2>
   
    <form method="post" class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Salvar</button>
    </form>
   
    <a href="{% url 'categoria_list' %}" class="btn">Voltar para a lista de categorias</a>
{% endblock %}

projeto/templates/categoria_list.html
{% extends 'base.html' %}
{% block title %}Lista de Categorias{% endblock %}
{% block content %}
<h2>Lista de Categorias</h2>
<ul>
    {% for categoria in object_list %}
    <li>{{ categoria.nome }} - <a class="btna" href="{% url 'categoria_update' categoria.pk %}">Editar</a> - <a class="btnv" href="{% url 'categoria_delete' categoria.pk %}">Excluir</a></li>
    {% endfor %}
</ul>
<a class="btn" href="{% url 'categoria_create' %}">Nova Categoria</a>
{% endblock %}

projeto/templates/produto_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Excluir Produto{% endblock %}

{% block content %}
    <h2>Excluir Produto</h2>

    <p>Tem certeza de que deseja excluir o produto <strong>{{ object.nome }}</strong>?</p>
   
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btnv">Confirmar Exclusão</button>
        <a class="btn" href="{% url 'produto_list' %}">Cancelar</a>
    </form>
{% endblock %}

projeto/templates/produto_form.html
{% extends 'base.html' %}

{% block title %}{% if object %}Editar Produto{% else %}Novo Produto{% endif %}{% endblock %}

{% block content %}
    <h2>{% if object %}Editar Produto{% else %}Novo Produto{% endif %}</h2>
   
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn" type="submit">Salvar</button>
    </form>
   
    <a class="btn" href="{% url 'produto_list' %}">Voltar para a lista de produtos</a>
{% endblock %}

projeto/templates/produto_list.html
{% extends 'base.html' %}

{% block title %}Lista de Produtos{% endblock %}

{% block content %}
    <h2>Lista de Produtos</h2>

    <div class="table-container"> <!-- Adicionando a div com a classe table-container -->
        <table>
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Preço</th>
                    <th>Categoria</th>
                    <th>Estado</th>
                    {% comment %} <th>Ações</th> {% endcomment %}
                </tr>
            </thead>
            <tbody>
                {% for produto in object_list %}
                <tr>
                    <td>{{ produto.nome }}</td>
                    <td>R$ {{ produto.valor }}</td>
                    <td>{{ produto.categoria.nome }}</td>
                    <td>{{ produto.estado }}</td>
                    <td id="btn-act">
                        <a href="{% url 'produto_update' produto.pk %}" class="btna">Editar</a>
                        <a href="{% url 'produto_delete' produto.pk %}" class="btnv">Excluir</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Nenhum produto cadastrado.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a class="btn" href="{% url 'produto_create' %}">Novo Produto</a>
    <a class="btn" href="{% url 'categoria_create' %}">Cadastrar Categoria</a>
{% endblock %}